name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    uses: ./github/workflows/setup-workspace.yaml@feat/playwright/setup

  linting:
    name: Run Linting, Formatting, and Typecheck
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: ./.github/actions/setup-job

      - name: Lint Check
        run: pnpm run lint

      - name: Format Check
        run: pnpm run format:verify

      - name: Typecheck
        run: pnpm run typecheck

  Tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: ./.github/actions/setup-job

      - name: Unit Tests
        run: pnpm run test
