name: CI

on: pull_request

jobs:
  setup:
    name: Setup Workspace
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hits }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'pnpm'

      - name: Install PNPM
        uses: pnpm/actions-setup@v4
        with:
          version: 8.6.3
          run_install: false

      - name: Cache PNPM Store
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-

      - name: Install Dependencies (cache missing)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --prefer-offline --config.ignore-scripts=true

  linting:
    name: Run linting, formatting, and typecheck
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'pnpm'

      - name: Install PNPM
        uses: pnpm/actions-setup@v4
        with:
          version: 8.6.3
          run_install: false

      - name: Use Cached Dependencies
        run: pnpm install --frozen-lockfile --offline

      - name: Lint Check
        run: pnpm run lint

      - name: Format Check
        run: pnpm run format:verify

      - name: Typecheck
        run: pnpm run typecheck
