name: E2E Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *' # Runs every day at 11:00 UTC (6:00 AM EST)

jobs:
  setup:
    uses: ./github/workflows/setup-workspace.yaml

  test:
    name: E2E Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-job

      - name: Install Playwright Browsers
        run: pnpm run postinstall:setup-playwright

      - name: Run E2e Tests
        run: pnpm run test:e2e

      - name: Upload E2E Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
